version: 2.1
workflows:
  version: 2.1
  dist-compile:
    jobs:
      - compile
jobs:
  compile:
    parallelism: 2
    docker:
      - image: gcc:9.3
    steps:
      - checkout
      #split all c files based on the index ID we're running on, pass subset to gcc compile
      - run: mkdir build && cd build
      # move compiled files to specific folder and persist to workspace
      - run: cmake ..
      - run: make -j2
